fullnameOverride: otel-collector
mode: deployment
replicaCount: 1

image:
  repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib
  tag: 0.160.0

command:
  name: otelcol-contrib

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 512Mi

ports:
  otlp:
    hostPort: null
  otlp-http:
    hostPort: null
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false

config:
  receivers:
    jaeger: null
    zipkin: null
    prometheus: null

  exporters:
    debug: null
    otlp/tempo:
      endpoint: tempo.monitoring.svc.cluster.local:4317
      tls:
        insecure: true
      sending_queue:
        enabled: true
        queue_size: 1000
      retry_on_failure:
        enabled: true
        max_elapsed_time: 300s

  service:
    pipelines:
      logs: null
      metrics: null
      traces:
        receivers: [otlp]
        processors: [memory_limiter, batch]
        exporters: [otlp/tempo]
