fullnameOverride: tempo
replicas: 1

tempo:
  retention: 24h
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 2Gi
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

persistence:
  enabled: true
  storageClassName: local-path
  size: 10Gi

service:
  type: ClusterIP
