apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ztunnel
  namespace: monitoring
  labels:
    release: monitoring
spec:
  jobLabel: app
  namespaceSelector:
    matchNames:
      - istio-system
  selector:
    matchLabels:
      app: ztunnel
  podMetricsEndpoints:
    - port: ztunnel-stats
      path: /stats/prometheus
      interval: 30s
